name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build requests

      - name: Get current PyPI version
        id: pypi_version
        run: echo "::set-output name=version::$(python -c 'import requests; print(requests.get("https://pypi.org/pypi/pyNekobin/json").json()["info"]["version"])')"

      - name: Set package version
        id: set_version
        run: |
          current_version=$(cat setup.py | grep version | head -n1 | cut -d'"' -f2)
          echo "::set-output name=version::${current_version}"

      - name: Compare package versions
        id: compare_versions
        run: |
          echo ${{ steps.set_version.outputs.version }}
          echo ${{ steps.pypi_version.outputs.version }}
          if [[ "${{ steps.set_version.outputs.version }}" != "${{ steps.pypi_version.outputs.version }}" ]]; then
            echo "Package version changed. Publishing to PyPI..."
          else
            echo "Package version is the same. Skipping PyPI publishing."
            exit 0
          fi

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PASSWORD }}
        run: twine upload dist/*
        if: steps.set_version.outputs.version != steps.pypi_version.outputs.version